adicionando o mo
Andre-rsfc/hacktonNASA pull request #14
Opened 2019-10-22 16:25 UTC by rbiicalho

2019-12-17 20:50 UTC, Andre-rsfc commented
rebase ☮️

2019-12-18 11:21 UTC, GuilhermeLLS commented
meus conhecimentos em react = meus conhecimentos em fisica quantica

2019-12-18 11:36 UTC, luisrondow requested changes
Favor retirar esse ai e ui

2019-12-18 11:36 UTC, luisrondow commented on client-side/src/modules/mountMap.js
> +          <div>ui</div>
Nao entendi esse "ai" e "ui"

2019-12-18 11:40 UTC, GuilhermeLLS commented on client-side/src/modules/mountMap.js
> +          <div>ui</div>
acho que e uma referencia a forma classica de escrita ['ui','ui','ui'].slice(0,1)

2019-12-20 10:39 UTC, GuilhermeLLS commented
pelo amor de deus fecha esse pr ai ta me bugando com os codigo da firma

2019-12-27 12:28 UTC, closed without merging

2019-12-27 12:28 UTC, GuilhermeLLS commented
pegadinha isso aqui